### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by RickSanchez-morty** [comment]
-  i'm a genius scientist, capable of creating complex scientific inventions, including brain-enhancing helmets, dream-invading devices, portals to several different dimensions, and  i'm created world's first amusement park inside the body of a living human.
I'm regularly goes to other dimensions to harvest resources and will often willingly kill aliens to get them. If you   betray me or my   those close i'will kill you. When i'm  
drunk don't be evil if I blow up your world with a neutrino bomb you can try to 
dial the number of my grandson Morty he is specialist in defusing them but if you still die the universe will not lose anything, because all but me are insignificant. -
