### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by RickSanchez-morty** [comment]
EXPERIENCE

2019 
Wiped Riku’s nose with a parallel universe where instead of science magic rages

2017 
Rick turned himself into a gherkin

2016
 Destroys intergalactic government by changing the price of their currency from 1$ to 0$

2015 
- Everyone who became a friend of Rick in the period 1996-2013 were killed at the Bird Person’s wedding by the intergalactic government
     
- Attempted suicide due to rejection of beloved Unity
     
- Put in an intergalactic prison

2014 
- Returned to the family and began intergalactic adventures with his grandson Morty
- Creates a serum that should help enchant Jessica to his grandson Morty. But when mixed with the flu virus, the serum causes an epidemic, all the inhabitants of the earth turned into kroninbergs
- Went to a parallel universe with grandson where another Rick corrected the situation and then died.

1996-2013
Strolling the universe and fought the intergalactic government became the most wanted criminal in the universe .

1996 
Left the family because he endangered their lives with his experiments.

1982 
Сreated a portal gun.

1981 
Вaughter Beth was born.

1980 
Married Diana.
