### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by RickSanchez-morty** [comment]
1980
Wedding with Diana.

1981
Вaughter Beth was born.

1982
Сreated a portal gun.

1996
Left the family because I endangered their lives with my experiments.

1996-2013
Life after leaving the family
Strolling the universe and fought the intergalactic government became the most wanted criminal in the universe.
Other information is classified

17th September 2014
Moving to a parallel universe
Creates a serum that should help enchant Jessica to my grandson Morty. But when mixed with the flu virus, the serum causes an epidemic, all the inhabitants of the earth turned into kroninbergs
Went to a parallel universe with grandson where another Rick corrected the situation and then died.

6th December 2013
Returned to the family and began intergalactic adventures with my grandson Morty

2015
Everyone who became a friend of me in the period 1996-2013 were killed at the Bird Person’s wedding by the intergalactic government
I'm try to suicide due to rejection of beloved Unity
Put in an intergalactic prison

2th April 2016
Destroys intergalactic government
There were many ways to destroy them, but I didn’t worry and just changed the value of their currency from $ 1 to 0

7th August 2017
I'm turned myself into a gherkin

9th December 2019
Wiped Riku’s nose with a parallel universe where instead of science magic rages with hepl's dragon
My daughter broke up with the loser and decided to take the whole family to a psychologist, but I don’t believe in such crap

2020
Chillil on another planet with Elon Task
