### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by RickSanchez-morty** [comment]
PERSONAL LIFE
7th January 2020

Chill on another planet with Elon TuskHis teeth confuse me

9th December 2019

Wiped Riku’s nose with a parallel universe where instead of science magic rages🧙 with helps dragon p.c The magic world is not the best place for a family vacation, these dragons are still perverts

7th August 2017

I'm turned myself into a gherkin

My daughter broke up with the loser and decided to take the whole family to a psychologist but I don’t believe in such cra*
2th April 2016

Destroys intergalactic government

There were many ways to destroy them, but I didn’t worry and just changed the value of their currency from $ 1 to 0
2015

It was a terrible year
17th September 2014

Moving to a parallel universe

Creates a serum that should help enchant Jessica to my grandson Morty. But when mixed with the flu virus, the serum causes an epidemic, all the inhabitants of the earth turned into kroninbergs
Went to a parallel universe with grandson where another Rick corrected the situation and then died.
6th December 2013

Returned to the family and began intergalactic adventures with my grandson Morty

1996-2013

Life after leaving the family

Strolling the universe and fought the intergalactic government became the most wanted criminal in the universe.
Other information is classified
1998

The best event in life

Tried Sichuan sauce from McDonals.😤
1996

Left the family because I endangered their lives with my experiments.

1982

Created a portal gunYes i'm cool

1981

Daughter Beth was born

I love this monster ❤️
1980

Wedding with Diana
